BEGIN TRANSACTION;
CREATE OR REPLACE VIEW employee_details AS SELECT e.emp_id emp_id,e.emp_name emp_name,e.salary salary,d.dept_name dept_name,d.location location FROM employees e JOIN departments d ON e.dept_id=d.dept_id;
CREATE OR REPLACE VIEW dept_statistics AS SELECT d.dept_id dept_id,d.dept_name dept_name,COUNT(e.emp_id) employee_count,COALESCE(ROUND(AVG(e.salary)::numeric,2),0) average_salary,COALESCE(MAX(e.salary),0) max_salary,COALESCE(MIN(e.salary),0) min_salary FROM departments d LEFT JOIN employees e ON d.dept_id=e.dept_id GROUP BY d.dept_id,d.dept_name;
CREATE OR REPLACE VIEW project_overview AS SELECT p.project_id project_id,p.project_name project_name,p.budget budget,d.dept_name dept_name,d.location location,COUNT(e.emp_id) FILTER (WHERE e.dept_id=d.dept_id) team_size FROM projects p JOIN departments d ON p.dept_id=d.dept_id LEFT JOIN employees e ON e.dept_id=d.dept_id GROUP BY p.project_id,p.project_name,p.budget,d.dept_name,d.location;
CREATE OR REPLACE VIEW high_earners AS SELECT e.emp_id emp_id,e.emp_name emp_name,e.salary salary,d.dept_name dept_name FROM employees e JOIN departments d ON e.dept_id=d.dept_id WHERE e.salary>55000;
ALTER VIEW high_earners RENAME TO top_performers;
CREATE TEMP VIEW temp_view AS SELECT emp_id,emp_name,dept_id,salary FROM employees WHERE salary<50000;
DROP VIEW IF EXISTS temp_view;
CREATE OR REPLACE VIEW employee_salaries AS SELECT emp_id,emp_name,dept_id,salary FROM employees WITH LOCAL CHECK OPTION;
UPDATE employee_salaries SET salary=52000 WHERE emp_name='John Smith';
INSERT INTO employee_salaries(emp_id,emp_name,dept_id,salary) VALUES (6,'Alice Johnson',102,58000);
CREATE OR REPLACE VIEW it_employees AS SELECT emp_id,emp_name,dept_id,salary FROM employees WHERE dept_id=101 WITH LOCAL CHECK OPTION;
INSERT INTO it_employees(emp_id,emp_name,dept_id,salary) VALUES (7,'Bob Wilson',103,60000);
CREATE MATERIALIZED VIEW dept_summary_mv AS SELECT d.dept_id dept_id,d.dept_name dept_name,COUNT(e.emp_id) total_employees,COALESCE(SUM(e.salary),0) total_salaries,COUNT(p.project_id) total_projects,COALESCE(SUM(p.budget),0) total_project_budget FROM departments d LEFT JOIN employees e ON d.dept_id=e.dept_id LEFT JOIN projects p ON d.dept_id=p.dept_id GROUP BY d.dept_id,d.dept_name WITH DATA;
SELECT * FROM dept_summary_mv ORDER BY total_employees DESC;
INSERT INTO employees(emp_id,emp_name,dept_id,salary) VALUES (8,'Charlie Brown',101,54000);
SELECT * FROM dept_summary_mv ORDER BY total_employees DESC;
REFRESH MATERIALIZED VIEW dept_summary_mv;
SELECT * FROM dept_summary_mv ORDER BY total_employees DESC;
CREATE UNIQUE INDEX IF NOT EXISTS idx_dept_summary_mv_dept_id ON dept_summary_mv(dept_id);
REFRESH MATERIALIZED VIEW CONCURRENTLY dept_summary_mv;
CREATE MATERIALIZED VIEW project_stats_mv WITH NO DATA AS SELECT p.project_id project_id,p.project_name project_name,p.budget budget,d.dept_name dept_name,COUNT(e.emp_id) assigned_employee_count FROM projects p JOIN departments d ON p.dept_id=d.dept_id LEFT JOIN employees e ON e.dept_id=d.dept_id GROUP BY p.project_id,p.project_name,p.budget,d.dept_name;
SELECT * FROM project_stats_mv;
REFRESH MATERIALIZED VIEW project_stats_mv;
CREATE ROLE analyst NOLOGIN;
CREATE ROLE data_viewer LOGIN PASSWORD 'viewer123';
CREATE ROLE report_user LOGIN PASSWORD 'report456';
CREATE ROLE db_creator LOGIN PASSWORD 'creator789' CREATEDB;
CREATE ROLE user_manager LOGIN PASSWORD 'manager101' CREATEROLE;
CREATE ROLE admin_user LOGIN PASSWORD 'admin999' SUPERUSER;
GRANT SELECT ON employees,departments,projects TO analyst;
GRANT ALL PRIVILEGES ON employee_details TO data_viewer;
GRANT SELECT,INSERT ON employees TO report_user;
CREATE ROLE hr_team NOLOGIN;
CREATE ROLE finance_team NOLOGIN;
CREATE ROLE it_team NOLOGIN;
CREATE ROLE hr_user1 LOGIN PASSWORD 'hr001';
CREATE ROLE hr_user2 LOGIN PASSWORD 'hr002';
CREATE ROLE finance_user1 LOGIN PASSWORD 'fin001';
GRANT hr_team TO hr_user1;
GRANT hr_team TO hr_user2;
GRANT finance_team TO finance_user1;
GRANT SELECT,UPDATE ON employees TO hr_team;
GRANT SELECT ON dept_statistics TO finance_team;
REVOKE UPDATE ON employees FROM hr_team;
REVOKE hr_team FROM hr_user2;
REVOKE ALL PRIVILEGES ON employee_details FROM data_viewer;
ALTER ROLE analyst WITH LOGIN PASSWORD 'analyst123';
ALTER ROLE user_manager WITH SUPERUSER;
ALTER ROLE analyst WITH PASSWORD NULL;
ALTER ROLE data_viewer WITH CONNECTION LIMIT 5;
CREATE ROLE read_only NOLOGIN;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_only;
CREATE ROLE junior_analyst LOGIN PASSWORD 'junior123';
CREATE ROLE senior_analyst LOGIN PASSWORD 'senior123';
GRANT read_only TO junior_analyst;
GRANT read_only TO senior_analyst;
GRANT INSERT,UPDATE ON employees TO senior_analyst;
CREATE ROLE project_manager LOGIN PASSWORD 'pm123';
ALTER VIEW dept_statistics OWNER TO project_manager;
ALTER TABLE projects OWNER TO project_manager;
CREATE ROLE temp_owner LOGIN;
CREATE TABLE IF NOT EXISTS temp_table(id INT);
ALTER TABLE temp_table OWNER TO temp_owner;
REASSIGN OWNED BY temp_owner TO postgres;
DROP OWNED BY temp_owner;
DROP ROLE IF EXISTS temp_owner;
CREATE OR REPLACE VIEW hr_employee_view AS SELECT emp_id,emp_name,dept_id,salary FROM employees WHERE dept_id=102;
GRANT SELECT ON hr_employee_view TO hr_team;
CREATE OR REPLACE VIEW finance_employee_view AS SELECT emp_id,emp_name,salary FROM employees;
GRANT SELECT ON finance_employee_view TO finance_team;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE OR REPLACE VIEW dept_dashboard AS SELECT d.dept_name dept_name,d.location location,COUNT(e.emp_id) employee_count,COALESCE(ROUND(AVG(e.salary)::numeric,2),0) average_salary,COUNT(p.project_id) FILTER (WHERE p.project_id IS NOT NULL) active_projects,COALESCE(SUM(p.budget),0) total_project_budget,COALESCE(ROUND((CASE WHEN COUNT(e.emp_id)=0 THEN 0 ELSE SUM(p.budget)::numeric/NULLIF(COUNT(e.emp_id),0) END)::numeric,2),0) budget_per_employee FROM departments d LEFT JOIN employees e ON d.dept_id=e.dept_id LEFT JOIN projects p ON d.dept_id=p.dept_id GROUP BY d.dept_name,d.location;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE OR REPLACE VIEW high_budget_projects AS SELECT p.project_id project_id,p.project_name project_name,p.budget budget,d.dept_name dept_name,p.created_date created_date,CASE WHEN p.budget>150000 THEN 'Critical Review Required' WHEN p.budget>100000 THEN 'Management Approval Needed' ELSE 'Standard Process' END approval_status FROM projects p JOIN departments d ON p.dept_id=d.dept_id WHERE p.budget>75000;
CREATE ROLE viewer_role NOLOGIN;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO viewer_role;
CREATE ROLE entry_role NOLOGIN;
GRANT viewer_role TO entry_role;
GRANT INSERT ON employees,projects TO entry_role;
CREATE ROLE analyst_role NOLOGIN;
GRANT entry_role TO analyst_role;
GRANT UPDATE ON employees,projects TO analyst_role;
CREATE ROLE manager_role NOLOGIN;
GRANT analyst_role TO manager_role;
GRANT DELETE ON employees,projects TO manager_role;
CREATE ROLE alice LOGIN PASSWORD 'alice123';
CREATE ROLE bob LOGIN PASSWORD 'bob123';
CREATE ROLE charlie LOGIN PASSWORD 'charlie123';
GRANT viewer_role TO alice;
GRANT analyst_role TO bob;
GRANT manager_role TO charlie;
COMMIT;
